### ISSUE TITLE
Upgrade to TailwindCSS v1.x

### ISSUE THREAD

**Issue by rasliche** [rasliche/bluestar-client#5]
Adam Wathan's argument for utility-first CSS: https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

Tailwind Docs: https://tailwindcss.com/
and free screencasts: https://tailwindcss.com/screencasts/

[Upgrade to v1 Guide](https://tailwindcss.com/docs/upgrading-to-v1)

**Comment by akoepcke** [comment]
Duplicate from #3 ?
Do you want some help with this?
